/*+++
ASTRAL.H
Author: Antonako1
Description: Astral header file
                Contains all Astral headers
                Include this file to include all Astral headers
Licensed under the MIT License
---*/

#pragma once
#ifndef ASTRAL_H
#define ASTRAL_H

#include <ASTRAL_STDINT.H>
#include <ASTRAL_API.H>
#include <ASTRAL_MEMORY.H>
#include <ASTRAL_MACROS.H>
#include <ASTRAL_STRING.H>
#include <ASTRAL_DEBUG.H>
#include <ASTRAL_CON.H>

#endif // ASTRAL_H